package com.github.l34130.netty.dbgw.protocol.postgres.constant

// https://www.postgresql.org/docs/current/protocol-error-fields.html
@Suppress("ktlint:standard:enum-entry-name-case", "EnumEntryName")
enum class ErrorField(
    val code: Int,
) {
    /**
     * Severity: the field contents are ERROR, FATAL, or PANIC (in an error message), or WARNING, NOTICE, DEBUG, INFO,
     * or LOG (in a notice message), or a localized translation of one of these.
     *
     * Always present.
     */
    S('S'.code),

    /**
     * Severity: the field contents are ERROR, FATAL, or PANIC (in an error message), or WARNING, NOTICE, DEBUG, INFO,
     * or LOG (in a notice message). This is identical to the S field except that the contents are never localized.
     *
     * This is present only in messages generated by PostgreSQL versions 9.6 and later.
     */
    V('V'.code),

    /**
     * Code: the SQLSTATE code for the error (see [Appendix A](https://www.postgresql.org/docs/current/errcodes-appendix.html)).
     *
     * Not localizable.
     *
     * Always present.
     */
    C('C'.code),

    /**
     * Message: the primary human-readable error message. This should be accurate but terse (typically one line).
     *
     * Always present.
     */
    M('M'.code),
    D('D'.code),
    H('H'.code),
    P('P'.code),
    p('p'.code),
    q('q'.code),
    W('W'.code),
    s('s'.code),
    t('t'.code),
    c('c'.code),
    d('d'.code),
    n('n'.code),
    F('F'.code),
    L('L'.code),
    R('R'.code),
    ;

    companion object {
        private val map = entries.associateBy { it.code }

        fun from(code: Int): ErrorField? = map[code]

        fun from(byte: Byte): ErrorField? = from(byte.toInt())
    }
}
