apiVersion: builtin/v1
kind: DatabaseTimeRangeAccessPolicy
metadata: {}
spec:
  range: "[00:00, 23:59]"
  action: ALLOW
---
apiVersion: builtin/v1
kind: DatabaseStatementTypePolicy
metadata: {}
spec:
  statements:
    - "SELECT"
    - "UPDATE"
    - "CREATE"
    - "DELETE"
  action: ALLOW
---
apiVersion: builtin/v1
kind: DatabaseResultSetMaskingPolicy
metadata: {}
spec:
  maskingRegex: "1234"
---
apiVersion: builtin/v1
kind: DatabaseResultSetMaskingPolicy
metadata: {}
spec:
  maskingRegex: "4567"
---
apiVersion: builtin/v1
kind: DatabaseRowLevelSecurityPolicy
metadata: {}
spec:
  column: .*id
  filterRegex: "[0-9]"
  action: ALLOW
---
apiVersion: builtin/v1
kind: DatabaseRowLevelSecurityPolicy
metadata: {}
spec:
  column: actor_id
  filter: '[1-9]'
  action: ALLOW